// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6BxSn4xyTQ1nxj03QhlJmzCRvfaIzp7s',
    appId: '1:29488011682:web:e8e6f407ed2cebcba27afb',
    messagingSenderId: '29488011682',
    projectId: 'prueba3-46207',
    authDomain: 'prueba3-46207.firebaseapp.com',
    storageBucket: 'prueba3-46207.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Pp1CidPeqBbtItO-tfFtmroVpnI1EH4',
    appId: '1:29488011682:android:1ab8b51fd19a681ea27afb',
    messagingSenderId: '29488011682',
    projectId: 'prueba3-46207',
    storageBucket: 'prueba3-46207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpfyTAvyI8iWyuk1wurB7pFXJLriG4MWc',
    appId: '1:29488011682:ios:700f31e7bdb28237a27afb',
    messagingSenderId: '29488011682',
    projectId: 'prueba3-46207',
    storageBucket: 'prueba3-46207.firebasestorage.app',
    iosBundleId: 'com.example.prueba3appmoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpfyTAvyI8iWyuk1wurB7pFXJLriG4MWc',
    appId: '1:29488011682:ios:700f31e7bdb28237a27afb',
    messagingSenderId: '29488011682',
    projectId: 'prueba3-46207',
    storageBucket: 'prueba3-46207.firebasestorage.app',
    iosBundleId: 'com.example.prueba3appmoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6BxSn4xyTQ1nxj03QhlJmzCRvfaIzp7s',
    appId: '1:29488011682:web:9f10801b3293c703a27afb',
    messagingSenderId: '29488011682',
    projectId: 'prueba3-46207',
    authDomain: 'prueba3-46207.firebaseapp.com',
    storageBucket: 'prueba3-46207.firebasestorage.app',
  );
}
